//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.common
{
   
/// <summary>
/// 测试用的账号
/// </summary>
public partial class TbTestAccountConfig
{
    private readonly Dictionary<int, common.TestAccountConfig> _dataMap;
    private readonly List<common.TestAccountConfig> _dataList;
    
    public TbTestAccountConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, common.TestAccountConfig>();
        _dataList = new List<common.TestAccountConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            common.TestAccountConfig _v;
            _v = common.TestAccountConfig.DeserializeTestAccountConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, common.TestAccountConfig> DataMap => _dataMap;
    public List<common.TestAccountConfig> DataList => _dataList;

    public common.TestAccountConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public common.TestAccountConfig Get(int key) => _dataMap[key];
    public common.TestAccountConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}