//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum ActType
    {
        Dmg = 0,
        OnlyAddBuff = 1,
        DmgBuff = 2,
        Heal = 3,
    }

} 
