//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum AoeType
    {
        /// <summary>
        /// 单体
        /// </summary>
        Single = 0,
        /// <summary>
        /// 目标和所在横排
        /// </summary>
        Horizontal = 1,
        /// <summary>
        /// 目标和所在竖排
        /// </summary>
        Vertical = 2,
        /// <summary>
        /// 全体
        /// </summary>
        All = 3,
        /// <summary>
        /// 目标和周围一圈
        /// </summary>
        Circle = 4,
        /// <summary>
        /// 生命值最低的单位
        /// </summary>
        Dying = 5,
        /// <summary>
        /// 目标附近十字
        /// </summary>
        Cross = 6,
    }

} 
