//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum AttrType
    {
        /// <summary>
        /// 力量
        /// </summary>
        STR = 0,
        /// <summary>
        /// 敏捷
        /// </summary>
        DEX = 1,
        /// <summary>
        /// 体质
        /// </summary>
        VIT = 2,
        /// <summary>
        /// 智力（不用）
        /// </summary>
        INTT = 3,
        /// <summary>
        /// 气
        /// </summary>
        QI = 4,
        MaxHp = 5,
        CurHp = 6,
        MaxShield = 7,
        CurShield = 8,
        MinAttack = 9,
        MaxAttack = 10,
        Attack = 11,
        HitRate = 12,
        Crit = 13,
        CritEffect = 14,
        Range = 15,
        Armor = 16,
        Dodge = 17,
        Parry = 18,
        AttackSpeed = 19,
        CastSpeed = 20,
        ResistFire = 21,
        ResistIce = 22,
        ResistThunder = 23,
        ResistYin = 24,
        ResistYang = 25,
        /// <summary>
        /// 26
        /// </summary>
        PhysicsDmg = 26,
        MagicDmg = 27,
        FireDmg = 28,
        IceDmg = 29,
        ThunderDmg = 30,
        YinDmg = 31,
        YangDmg = 32,
        HealEffect = 33,
        BurnDmg = 34,
        PosionDmg = 35,
        BleedDmg = 36,
        AllDmg = 37,
        HpDrain = 38,
        DmgReflect = 39,
        CoolDown = 40,
        HpPct = 41,
        CoolDownFix = 42,
        CDMult = 43,
        /// <summary>
        /// 复活进度
        /// </summary>
        ReviveTime = 44,
        DmgTaken = 45,
        /// <summary>
        /// 其他取值伤害
        /// </summary>
        OtherDmg = 46,
        /// <summary>
        /// 护盾回复延迟
        /// </summary>
        ShdRegDelay = 47,
        /// <summary>
        /// 护盾回满时长
        /// </summary>
        ShdRegTime = 48,
        MagicResist = 49,
        HpPctFix = 1002,
        HpAdd = 1003,
        ShdPctFix = 1005,
        ShdAdd = 1006,
    }

} 
