//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum CompareType
    {
        Largger = 0,
        Smaller = 1,
        Equal = 2,
        LarggerAndEqual = 3,
        SmallerAndEqual = 4,
    }

} 
