//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum CoreAttr
    {
        /// <summary>
        /// 敏捷
        /// </summary>
        DEX = 0,
        /// <summary>
        /// 体质
        /// </summary>
        VIT = 1,
        /// <summary>
        /// 炁
        /// </summary>
        QI = 2,
    }

} 
