//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum DirType
    {
        /// <summary>
        /// 左
        /// </summary>
        L = 0,
        /// <summary>
        /// 右
        /// </summary>
        R = 1,
        /// <summary>
        /// 前
        /// </summary>
        F = 2,
        /// <summary>
        /// 后
        /// </summary>
        B = 3,
        /// <summary>
        /// 左前
        /// </summary>
        LF = 4,
        /// <summary>
        /// 右前
        /// </summary>
        RF = 5,
        /// <summary>
        /// 左后
        /// </summary>
        LB = 6,
        /// <summary>
        /// 右后
        /// </summary>
        RB = 7,
    }

} 
