//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg
{
    public enum FGUIType
    {
        /// <summary>
        /// 0
        /// </summary>
        Default = 0,
        /// <summary>
        /// 1
        /// </summary>
        Loading = 1,
        /// <summary>
        /// 2
        /// </summary>
        Login = 2,
        /// <summary>
        /// 3
        /// </summary>
        Background = 3,
        /// <summary>
        /// 4
        /// </summary>
        Lobby = 4,
        /// <summary>
        /// 5
        /// </summary>
        ZesuDemoSelect = 5,
        /// <summary>
        /// 6
        /// </summary>
        AnimatorDemo = 6,
        /// <summary>
        /// 7
        /// </summary>
        BattleDemo = 7,
        /// <summary>
        /// 1001
        /// </summary>
        BattleGround = 8,
        /// <summary>
        /// 1002
        /// </summary>
        BattleResult = 9,
        /// <summary>
        /// 1003
        /// </summary>
        BattleVs = 10,
        /// <summary>
        /// 1004
        /// </summary>
        BottomCheck = 11,
        /// <summary>
        /// 1005
        /// </summary>
        CharacterDialog = 12,
        /// <summary>
        /// 1006
        /// </summary>
        Clan = 13,
        /// <summary>
        /// 1007
        /// </summary>
        CommonSelectList = 14,
        /// <summary>
        /// 1008
        /// </summary>
        EmojiSelect = 15,
        /// <summary>
        /// 1009
        /// </summary>
        ErrorNetwork = 16,
        /// <summary>
        /// 1010
        /// </summary>
        GameStatus = 17,
        /// <summary>
        /// 1011
        /// </summary>
        Inventory = 18,
        /// <summary>
        /// 1012
        /// </summary>
        MJRoom = 19,
        /// <summary>
        /// 1013
        /// </summary>
        NormalActionSelect = 20,
        /// <summary>
        /// 1014
        /// </summary>
        Play = 21,
        /// <summary>
        /// 1015
        /// </summary>
        PopupConfirm = 22,
        /// <summary>
        /// 1016
        /// </summary>
        PopupInput = 23,
        /// <summary>
        /// 1017
        /// </summary>
        PopupSelect = 24,
        /// <summary>
        /// 1018
        /// </summary>
        SelectServer = 25,
        /// <summary>
        /// 1019
        /// </summary>
        Setting = 26,
        /// <summary>
        /// 1020
        /// </summary>
        SetUsername = 27,
        /// <summary>
        /// 1021
        /// </summary>
        SlgPlay = 28,
        /// <summary>
        /// 1022
        /// </summary>
        Rank = 29,
        /// <summary>
        /// 1023
        /// </summary>
        Chat = 30,
        /// <summary>
        /// 1024
        /// </summary>
        Notice = 31,
        /// <summary>
        /// 1025
        /// </summary>
        Othello = 32,
        /// <summary>
        /// 1026
        /// </summary>
        AFKMain = 33,
        /// <summary>
        /// 1027
        /// </summary>
        AFKBattle = 34,
        /// <summary>
        /// 1028
        /// </summary>
        AFKUnitInfo = 35,
    }
}
