//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum LevelType
    {
        CharLv = 0,
        AscendLv = 1,
        ClothLv = 2,
        WeaponLv = 3,
        WeaponAscendLv = 4,
    }

} 
