//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum RangeType
    {
        Random = 0,
        Nearest = 1,
        Farthest = 2,
        All = 3,
        /// <summary>
        /// 自己
        /// </summary>
        Self = 4,
        /// <summary>
        /// 链接对象
        /// </summary>
        LinkTo = 5,
        /// <summary>
        /// 最高血量
        /// </summary>
        HighestPctHp = 6,
        /// <summary>
        /// 最低血量
        /// </summary>
        LowestPctHp = 7,
        /// <summary>
        /// 最高攻击力
        /// </summary>
        HighestScore = 8,
        Counter = 9,
        /// <summary>
        /// 最远排最近列
        /// </summary>
        FarthestCounter = 10,
    }

} 
