//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum SkillType
    {
        /// <summary>
        /// 主动技
        /// </summary>
        Active = 0,
        /// <summary>
        /// 被动技
        /// </summary>
        Passive = 1,
        /// <summary>
        /// 领域技
        /// </summary>
        Field = 2,
    }

} 
