//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum StateType
    {
        /// <summary>
        /// 隐身
        /// </summary>
        Invisible = 10000,
        /// <summary>
        /// 无敌
        /// </summary>
        Invincible = 10001,
        /// <summary>
        /// 眩晕
        /// </summary>
        Stun = 10002,
        /// <summary>
        /// 移动
        /// </summary>
        Moving = 10003,
    }

} 
