//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum TagType
    {
        Fire = 2001,
        Ice = 2002,
        Thunder = 2003,
        Yin = 2004,
        Yang = 2005,
        Physics = 2006,
        Magic = 2007,
        Heal = 2008,
        Dmg = 2009,
        Burn = 2010,
        Bleed = 2011,
        Posion = 2012,
        Move = 2013,
        Shd = 2014,
    }

} 
