//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum TargetType
    {
        Enemy = 0,
        Friend = 1,
        Self = 2,
        LinkTo = 3,
        LinkFrom = 4,
        Caster = 5,
        Previous = 6,
        EmptyGrid = 7,
        FieldMate = 8,
        Manual = 9,
    }

} 
