//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum UnitType
    {
        /// <summary>
        /// 角色
        /// </summary>
        Creature = 0,
        /// <summary>
        /// 非角色
        /// </summary>
        Ability = 1,
        Supporter = 2,
        Tank = 3,
        Dps = 4,
    }

} 
