//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.zerg
{

public sealed partial class AreaSize :  Bright.Config.BeanBase 
{
    public AreaSize(ByteBuf _buf) 
    {
        X = _buf.ReadInt();
        Y = _buf.ReadInt();
        PostInit();
    }

    public static AreaSize DeserializeAreaSize(ByteBuf _buf)
    {
        return new zerg.AreaSize(_buf);
    }

    public int X { get; private set; }
    public int Y { get; private set; }

    public const int __ID__ = -1883119140;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
