//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.zerg
{

/// <summary>
/// 蓝图
/// </summary>
public sealed partial class BluePrintConfig :  Bright.Config.BeanBase 
{
    public BluePrintConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Type = (zerg.BuildingType)_buf.ReadInt();
        Level = _buf.ReadInt();
        Rare = _buf.ReadInt();
        Cost = _buf.ReadInt();
        LinkBuilding = _buf.ReadString();
        PostInit();
    }

    public static BluePrintConfig DeserializeBluePrintConfig(ByteBuf _buf)
    {
        return new zerg.BluePrintConfig(_buf);
    }

    public string Id { get; private set; }
    public string Name { get; private set; }
    public zerg.BuildingType Type { get; private set; }
    public int Level { get; private set; }
    public int Rare { get; private set; }
    public int Cost { get; private set; }
    public string LinkBuilding { get; private set; }

    public const int __ID__ = -1074881497;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Level:" + Level + ","
        + "Rare:" + Rare + ","
        + "Cost:" + Cost + ","
        + "LinkBuilding:" + LinkBuilding + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
