
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.zerg
{
    /// <summary>
    /// 牌的类型
    /// </summary>
    public enum CardType
    {
        /// <summary>
        /// 建筑
        /// </summary>
        Building = 0,
        /// <summary>
        /// 技能
        /// </summary>
        Skill = 1,
        /// <summary>
        /// 召唤牌
        /// </summary>
        Module = 2,
    }
}
