
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.hunter
{

/// <summary>
/// 卡牌
/// </summary>
public sealed class CardConfig :  Bright.Config.BeanBase 
{
    public CardConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Cost = _buf.ReadInt();
    }

    public static CardConfig DeserializeCardConfig(ByteBuf _buf)
    {
        return new hunter.CardConfig(_buf);
    }

    /// <summary>
    /// 卡牌id
    /// </summary>
    public int Id { get; private set; }
    public string Name { get; private set; }
    public string Desc { get; private set; }
    public int Cost { get; private set; }

    public const int __ID__ = -1688655424;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Cost:" + Cost + ","
        + "}";
    }
    }

}
