
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.hunter
{
    /// <summary>
    /// 道具品质
    /// </summary>
    public enum CardType
    {
        /// <summary>
        /// 白
        /// </summary>
        Action = 0,
        /// <summary>
        /// 白
        /// </summary>
        Response = 1,
    }
}
