//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg
{
    public enum FGUIType
    {
        /// <summary>
        /// 0
        /// </summary>
        Default = 0,
        /// <summary>
        /// 1
        /// </summary>
        Loading = 1,
        /// <summary>
        /// 2
        /// </summary>
        Login = 2,
        /// <summary>
        /// 3
        /// </summary>
        Background = 3,
        /// <summary>
        /// 4
        /// </summary>
        Lobby = 4,
        /// <summary>
        /// 5
        /// </summary>
        ZesuDemoSelect = 5,
        /// <summary>
        /// 6
        /// </summary>
        AnimatorDemo = 6,
        /// <summary>
        /// 7
        /// </summary>
        BattleDemo = 7,
        /// <summary>
        /// 8
        /// </summary>
        HunterBattle = 8,
        /// <summary>
        /// 9
        /// </summary>
        BulePrintStore = 9,
    }
}
