//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
public sealed partial class AttrTypeEx :  Bright.Config.BeanBase 
{
    public AttrTypeEx(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        AttrFormat = (AttrFormat)_buf.ReadInt();
        PostInit();
    }

    public static AttrTypeEx DeserializeAttrTypeEx(ByteBuf _buf)
    {
        return new afk.AttrTypeEx(_buf);
    }

    public int Id { get; private set; }
    public string Name { get; private set; }
    public AttrFormat AttrFormat { get; private set; }

    public const int __ID__ = 33658118;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "AttrFormat:" + AttrFormat + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}