//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
public sealed partial class Cloths :  Bright.Config.BeanBase 
{
    public Cloths(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        LanName = _buf.ReadString();
        LanText1 = _buf.ReadString();
        PPCost = _buf.ReadInt();
        CastingTime = _buf.ReadInt();
        ChannelingTime = _buf.ReadInt();
        CoolDown = _buf.ReadInt();
        Active1 = _buf.ReadString();
        Active2 = _buf.ReadString();
        Active3 = _buf.ReadString();
        Active4 = _buf.ReadString();
        Active5 = _buf.ReadString();
        Passive1 = _buf.ReadString();
        Passive2 = _buf.ReadString();
        Passive3 = _buf.ReadString();
        Passive4 = _buf.ReadString();
        Passive5 = _buf.ReadString();
        SkillMult = _buf.ReadFloat();
        Val1 = _buf.ReadFloat();
        Val2 = _buf.ReadFloat();
        Val3 = _buf.ReadFloat();
        Val4 = _buf.ReadFloat();
        Val5 = _buf.ReadFloat();
        PostInit();
    }

    public static Cloths DeserializeCloths(ByteBuf _buf)
    {
        return new afk.Cloths(_buf);
    }

    public string Id { get; private set; }
    public string Name { get; private set; }
    public string LanName { get; private set; }
    public string LanText1 { get; private set; }
    public int PPCost { get; private set; }
    public int CastingTime { get; private set; }
    public int ChannelingTime { get; private set; }
    public int CoolDown { get; private set; }
    public string Active1 { get; private set; }
    public string Active2 { get; private set; }
    public string Active3 { get; private set; }
    public string Active4 { get; private set; }
    public string Active5 { get; private set; }
    public string Passive1 { get; private set; }
    public string Passive2 { get; private set; }
    public string Passive3 { get; private set; }
    public string Passive4 { get; private set; }
    public string Passive5 { get; private set; }
    public float SkillMult { get; private set; }
    public float Val1 { get; private set; }
    public float Val2 { get; private set; }
    public float Val3 { get; private set; }
    public float Val4 { get; private set; }
    public float Val5 { get; private set; }

    public const int __ID__ = 135221185;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "LanName:" + LanName + ","
        + "LanText1:" + LanText1 + ","
        + "PPCost:" + PPCost + ","
        + "CastingTime:" + CastingTime + ","
        + "ChannelingTime:" + ChannelingTime + ","
        + "CoolDown:" + CoolDown + ","
        + "Active1:" + Active1 + ","
        + "Active2:" + Active2 + ","
        + "Active3:" + Active3 + ","
        + "Active4:" + Active4 + ","
        + "Active5:" + Active5 + ","
        + "Passive1:" + Passive1 + ","
        + "Passive2:" + Passive2 + ","
        + "Passive3:" + Passive3 + ","
        + "Passive4:" + Passive4 + ","
        + "Passive5:" + Passive5 + ","
        + "SkillMult:" + SkillMult + ","
        + "Val1:" + Val1 + ","
        + "Val2:" + Val2 + ","
        + "Val3:" + Val3 + ","
        + "Val4:" + Val4 + ","
        + "Val5:" + Val5 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}