//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
public sealed partial class FormuluaEx :  Bright.Config.BeanBase 
{
    public FormuluaEx(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Params = _buf.ReadString();
        PostInit();
    }

    public static FormuluaEx DeserializeFormuluaEx(ByteBuf _buf)
    {
        return new afk.FormuluaEx(_buf);
    }

    public string Id { get; private set; }
    public string Params { get; private set; }

    public const int __ID__ = 1098125154;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Params:" + Params + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}