//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
public sealed partial class GameConfig :  Bright.Config.BeanBase 
{
    public GameConfig(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Value = _buf.ReadString();
        PostInit();
    }

    public static GameConfig DeserializeGameConfig(ByteBuf _buf)
    {
        return new afk.GameConfig(_buf);
    }

    public string Key { get; private set; }
    public string Value { get; private set; }

    public const int __ID__ = 373068796;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}