//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
public sealed partial class Resource :  Bright.Config.BeanBase 
{
    public Resource(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Icon1 = _buf.ReadString();
        Icon2 = _buf.ReadString();
        Frame1 = _buf.ReadString();
        Frame2 = _buf.ReadString();
        PictrueSmall = _buf.ReadString();
        PictrueMiddle = _buf.ReadString();
        PictrueBig = _buf.ReadString();
        Sound = _buf.ReadString();
        Text = _buf.ReadString();
        TextLong = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Color1 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Color1.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Color2 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Color2.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Color3 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Color3.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Color4 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Color4.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Color5 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Color5.Add(_e0);}}
        PostInit();
    }

    public static Resource DeserializeResource(ByteBuf _buf)
    {
        return new afk.Resource(_buf);
    }

    public string Id { get; private set; }
    public string Name { get; private set; }
    public string Icon1 { get; private set; }
    public string Icon2 { get; private set; }
    public string Frame1 { get; private set; }
    public string Frame2 { get; private set; }
    public string PictrueSmall { get; private set; }
    public string PictrueMiddle { get; private set; }
    public string PictrueBig { get; private set; }
    public string Sound { get; private set; }
    public string Text { get; private set; }
    public string TextLong { get; private set; }
    public System.Collections.Generic.List<int> Color1 { get; private set; }
    public System.Collections.Generic.List<int> Color2 { get; private set; }
    public System.Collections.Generic.List<int> Color3 { get; private set; }
    public System.Collections.Generic.List<int> Color4 { get; private set; }
    public System.Collections.Generic.List<int> Color5 { get; private set; }

    public const int __ID__ = -336378826;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Icon1:" + Icon1 + ","
        + "Icon2:" + Icon2 + ","
        + "Frame1:" + Frame1 + ","
        + "Frame2:" + Frame2 + ","
        + "PictrueSmall:" + PictrueSmall + ","
        + "PictrueMiddle:" + PictrueMiddle + ","
        + "PictrueBig:" + PictrueBig + ","
        + "Sound:" + Sound + ","
        + "Text:" + Text + ","
        + "TextLong:" + TextLong + ","
        + "Color1:" + Bright.Common.StringUtil.CollectionToString(Color1) + ","
        + "Color2:" + Bright.Common.StringUtil.CollectionToString(Color2) + ","
        + "Color3:" + Bright.Common.StringUtil.CollectionToString(Color3) + ","
        + "Color4:" + Bright.Common.StringUtil.CollectionToString(Color4) + ","
        + "Color5:" + Bright.Common.StringUtil.CollectionToString(Color5) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}