//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
   
/// <summary>
/// Buff表
/// </summary>
public partial class TbBuff
{
    private readonly Dictionary<string, afk.Buff> _dataMap;
    private readonly List<afk.Buff> _dataList;
    
    public TbBuff(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, afk.Buff>();
        _dataList = new List<afk.Buff>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            afk.Buff _v;
            _v = afk.Buff.DeserializeBuff(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, afk.Buff> DataMap => _dataMap;
    public List<afk.Buff> DataList => _dataList;

    public afk.Buff GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public afk.Buff Get(string key) => _dataMap[key];
    public afk.Buff this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}