//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
   
public partial class TbGameConfig
{
    private readonly Dictionary<string, afk.GameConfig> _dataMap;
    private readonly List<afk.GameConfig> _dataList;
    
    public TbGameConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, afk.GameConfig>();
        _dataList = new List<afk.GameConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            afk.GameConfig _v;
            _v = afk.GameConfig.DeserializeGameConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
        PostInit();
    }

    public Dictionary<string, afk.GameConfig> DataMap => _dataMap;
    public List<afk.GameConfig> DataList => _dataList;

    public afk.GameConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public afk.GameConfig Get(string key) => _dataMap[key];
    public afk.GameConfig this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}