//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
   
public partial class TbLevelUp
{
    private readonly Dictionary<string, afk.LevelUp> _dataMap;
    private readonly List<afk.LevelUp> _dataList;
    
    public TbLevelUp(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, afk.LevelUp>();
        _dataList = new List<afk.LevelUp>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            afk.LevelUp _v;
            _v = afk.LevelUp.DeserializeLevelUp(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, afk.LevelUp> DataMap => _dataMap;
    public List<afk.LevelUp> DataList => _dataList;

    public afk.LevelUp GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public afk.LevelUp Get(string key) => _dataMap[key];
    public afk.LevelUp this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}