//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
   
/// <summary>
/// 技能表
/// </summary>
public partial class TbSkill
{
    private readonly Dictionary<string, afk.Skill> _dataMap;
    private readonly List<afk.Skill> _dataList;
    
    public TbSkill(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, afk.Skill>();
        _dataList = new List<afk.Skill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            afk.Skill _v;
            _v = afk.Skill.DeserializeSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, afk.Skill> DataMap => _dataMap;
    public List<afk.Skill> DataList => _dataList;

    public afk.Skill GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public afk.Skill Get(string key) => _dataMap[key];
    public afk.Skill this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}