//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
public sealed partial class Unit :  Bright.Config.BeanBase 
{
    public Unit(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Type = (UnitType)_buf.ReadInt();
        Targeted = _buf.ReadBool();
        Rare = _buf.ReadInt();
        STR = _buf.ReadInt();
        ReviveTime = _buf.ReadInt();
        MoveStyle = (MoveStyle)_buf.ReadInt();
        DEX = _buf.ReadInt();
        VIT = _buf.ReadInt();
        QI = _buf.ReadInt();
        Skill1 = _buf.ReadString();
        Skill2 = _buf.ReadString();
        Skill3 = _buf.ReadString();
        Skill4 = _buf.ReadString();
        Skill5 = _buf.ReadString();
        Skill6 = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PassiveBuff = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); PassiveBuff.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AscendLvGrowth = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); AscendLvGrowth.Add(_e0);}}
        ResourceId = _buf.ReadString();
        LanName = _buf.ReadString();
        LanText1 = _buf.ReadString();
        InVerson = _buf.ReadBool();
        PostInit();
    }

    public static Unit DeserializeUnit(ByteBuf _buf)
    {
        return new afk.Unit(_buf);
    }

    public string Id { get; private set; }
    public string Name { get; private set; }
    public UnitType Type { get; private set; }
    public bool Targeted { get; private set; }
    public int Rare { get; private set; }
    public int STR { get; private set; }
    public int ReviveTime { get; private set; }
    public MoveStyle MoveStyle { get; private set; }
    public int DEX { get; private set; }
    public int VIT { get; private set; }
    public int QI { get; private set; }
    public string Skill1 { get; private set; }
    public string Skill2 { get; private set; }
    public string Skill3 { get; private set; }
    public string Skill4 { get; private set; }
    public string Skill5 { get; private set; }
    public string Skill6 { get; private set; }
    public System.Collections.Generic.List<string> PassiveBuff { get; private set; }
    public System.Collections.Generic.List<float> AscendLvGrowth { get; private set; }
    public string ResourceId { get; private set; }
    public string LanName { get; private set; }
    public string LanText1 { get; private set; }
    public bool InVerson { get; private set; }

    public const int __ID__ = 693415340;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Targeted:" + Targeted + ","
        + "Rare:" + Rare + ","
        + "STR:" + STR + ","
        + "ReviveTime:" + ReviveTime + ","
        + "MoveStyle:" + MoveStyle + ","
        + "DEX:" + DEX + ","
        + "VIT:" + VIT + ","
        + "QI:" + QI + ","
        + "Skill1:" + Skill1 + ","
        + "Skill2:" + Skill2 + ","
        + "Skill3:" + Skill3 + ","
        + "Skill4:" + Skill4 + ","
        + "Skill5:" + Skill5 + ","
        + "Skill6:" + Skill6 + ","
        + "PassiveBuff:" + Bright.Common.StringUtil.CollectionToString(PassiveBuff) + ","
        + "AscendLvGrowth:" + Bright.Common.StringUtil.CollectionToString(AscendLvGrowth) + ","
        + "ResourceId:" + ResourceId + ","
        + "LanName:" + LanName + ","
        + "LanText1:" + LanText1 + ","
        + "InVerson:" + InVerson + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}