//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.afk
{
public sealed partial class UnitGroup :  Bright.Config.BeanBase 
{
    public UnitGroup(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Level = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Level.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rank = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Rank.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Talisman = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Talisman.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Cloths = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Cloths.Add(_e0);}}
        Slot1 = _buf.ReadString();
        Slot2 = _buf.ReadString();
        Slot3 = _buf.ReadString();
        Slot4 = _buf.ReadString();
        Slot5 = _buf.ReadString();
        Slot6 = _buf.ReadString();
        Slot7 = _buf.ReadString();
        Slot8 = _buf.ReadString();
        Slot9 = _buf.ReadString();
        Slot10 = _buf.ReadString();
        Slot11 = _buf.ReadString();
        Slot12 = _buf.ReadString();
        PostInit();
    }

    public static UnitGroup DeserializeUnitGroup(ByteBuf _buf)
    {
        return new afk.UnitGroup(_buf);
    }

    public string Id { get; private set; }
    public string Name { get; private set; }
    public System.Collections.Generic.List<int> Level { get; private set; }
    public System.Collections.Generic.List<int> Rank { get; private set; }
    public System.Collections.Generic.List<string> Talisman { get; private set; }
    public System.Collections.Generic.List<string> Cloths { get; private set; }
    public string Slot1 { get; private set; }
    public string Slot2 { get; private set; }
    public string Slot3 { get; private set; }
    public string Slot4 { get; private set; }
    public string Slot5 { get; private set; }
    public string Slot6 { get; private set; }
    public string Slot7 { get; private set; }
    public string Slot8 { get; private set; }
    public string Slot9 { get; private set; }
    public string Slot10 { get; private set; }
    public string Slot11 { get; private set; }
    public string Slot12 { get; private set; }

    public const int __ID__ = -349240269;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Level:" + Bright.Common.StringUtil.CollectionToString(Level) + ","
        + "Rank:" + Bright.Common.StringUtil.CollectionToString(Rank) + ","
        + "Talisman:" + Bright.Common.StringUtil.CollectionToString(Talisman) + ","
        + "Cloths:" + Bright.Common.StringUtil.CollectionToString(Cloths) + ","
        + "Slot1:" + Slot1 + ","
        + "Slot2:" + Slot2 + ","
        + "Slot3:" + Slot3 + ","
        + "Slot4:" + Slot4 + ","
        + "Slot5:" + Slot5 + ","
        + "Slot6:" + Slot6 + ","
        + "Slot7:" + Slot7 + ","
        + "Slot8:" + Slot8 + ","
        + "Slot9:" + Slot9 + ","
        + "Slot10:" + Slot10 + ","
        + "Slot11:" + Slot11 + ","
        + "Slot12:" + Slot12 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}