//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.zerg
{
    /// <summary>
    /// 牌的类型
    /// </summary>
    public enum GroundType
    {
        /// <summary>
        /// 无要求
        /// </summary>
        None = 0,
        /// <summary>
        /// 空地
        /// </summary>
        Empty = 1,
        /// <summary>
        /// 障碍
        /// </summary>
        Barrier = 2,
        /// <summary>
        /// 矿物
        /// </summary>
        Mineral = 3,
    }
}
