//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.zerg
{
   
/// <summary>
/// 建筑表
/// </summary>
public partial class TbBuilding
{
    private readonly Dictionary<string, zerg.BuildingConfig> _dataMap;
    private readonly List<zerg.BuildingConfig> _dataList;
    
    public TbBuilding(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, zerg.BuildingConfig>();
        _dataList = new List<zerg.BuildingConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            zerg.BuildingConfig _v;
            _v = zerg.BuildingConfig.DeserializeBuildingConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, zerg.BuildingConfig> DataMap => _dataMap;
    public List<zerg.BuildingConfig> DataList => _dataList;

    public zerg.BuildingConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public zerg.BuildingConfig Get(string key) => _dataMap[key];
    public zerg.BuildingConfig this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}