
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.hunter
{
    /// <summary>
    /// 牌的类型
    /// </summary>
    public enum CardType
    {
        /// <summary>
        /// 只有自己的行动阶段可以使用的牌。打出后进入堆叠，不论成功结算与否都进入弃牌区。
        /// </summary>
        Skill = 0,
        /// <summary>
        /// 随时可以使用的牌。打出后进入堆叠，不论成功结算与否都进入弃牌区。
        /// </summary>
        Counter = 1,
        /// <summary>
        /// 成功结算则停留在战斗区，否则进入弃牌区；若不被外来效果移除，会永久存在。
        /// </summary>
        Summon = 2,
    }
}
