
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.hunter
{
   
/// <summary>
/// 道具表
/// </summary>
public sealed class TbCardConfig
{
    private readonly Dictionary<int, hunter.CardConfig> _dataMap;
    private readonly List<hunter.CardConfig> _dataList;
    
    public TbCardConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, hunter.CardConfig>();
        _dataList = new List<hunter.CardConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            hunter.CardConfig _v;
            _v = hunter.CardConfig.DeserializeCardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, hunter.CardConfig> DataMap => _dataMap;
    public List<hunter.CardConfig> DataList => _dataList;

    public hunter.CardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public hunter.CardConfig Get(int key) => _dataMap[key];
    public hunter.CardConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
}

}